on:
  push:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Caching Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/avd/*
            ~/.android/adb*

          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Testing
        run: ./gradlew test

      - name: Run Integration testing
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          profile: Nexus 6
          emulator-build: 7425822
          force-avd-creation: false
          arch: arm64-v8a
          emulator-options: -no-window -noaudio -no-boot-anim -camera-back
          script: ./gradlew connectedCheck
